import assert from 'node:assert/strict';
import {analyze,meld,deal,act} from '../lib/game.ts';
const cs=(rs,s=0)=>rs.map((r,i)=>({r,s,id:`${s}-${r}-${i}`}));
assert.deepEqual(meld(cs([1,2,3]),9),[2,1]);
assert.deepEqual(meld(cs([12,13,1]),9),[2,1]);
assert.deepEqual(meld(cs([13,1,2]),9),[]);
assert.equal(meld([...cs([3,4]),...cs([0])],9).includes(1),true);
assert.equal(meld([...cs([3,4]),...cs([0])],9).includes(2),false);
assert.deepEqual(meld(cs([7,7,7]),9),[]);
assert.equal(meld([{r:7,s:0},{r:7,s:1},{r:7,s:2}],9).includes(0),true);
const winning=[...cs([1,2,3]),...cs([4,5,6],1),...cs([9,10,11,12],2),{r:8,s:0},{r:8,s:1},{r:8,s:2}];
assert.equal(analyze(winning,13).valid,true);
assert.equal(analyze(winning,13).penalty,0);
const impure=[...cs([1,2,3]),...cs([4,0,6],1),...cs([9,10,11,12],2),{r:8,s:0},{r:8,s:1},{r:8,s:2}];
assert.equal(analyze(impure,13).valid,true);
assert.equal(analyze(cs([2,4,6,8,10,12,2,4,6,8,10,12,13]),1).valid,false);
const g={players:[{name:'A',hand:[],score:0,draws:0},{name:'B',hand:[],score:0,draws:0}],history:[],round:0};deal(g);
assert.equal(g.players[0].hand.length,13);assert.equal(g.deck.length,78);
assert.equal(new Set([...g.deck,...g.pile,g.wild,...g.players.flatMap(p=>p.hand)].map(c=>c.id)).size,106);
assert.throws(()=>act(g,1,'draw'));act(g,0,'draw');assert.equal(g.players[0].hand.length,14);assert.throws(()=>act(g,0,'draw'));act(g,0,'discard',g.players[0].hand[0].id);assert.equal(g.turn,1);act(g,1,'drop');assert.equal(g.players[1].score,20);act(g,0,'next');assert.equal(g.round,2);assert.equal(g.players[1].score,20);
const noPure=[...cs([2,4,6,8],0),...cs([2,4,6,8],1),...cs([2,4,6,8],2),...cs([10],3)];assert.equal(analyze(noPure,13).penalty,70);
console.log('PASS: pure/impure sequences, aces, duplicate sets, full declaration, scoring, shuffle/deal, turn enforcement, drops and next round.');
